apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: public.ecr.aws/h9h4h9i4/wanderlust-frontend:latest
        imagePullPolicy: Always
        env:
          - name: VITE_API_PATH
            value: "http://a552e389d84244fbd957d0a37d0d4d1e-1599631205.us-west-2.elb.amazonaws.com"
        ports:
        - containerPort: 5173
